### ISSUE TITLE
[HELP_WANTED] Entity training and Prediction

### ISSUE THREAD

**Issue by SraavanChevireddy** [AdirthaBorgohain/NER-RE#3]
Hello Adirtha - Upon your last suggestion I'm able to train the model. I got some good P-R-F Scores. But when I try to make a prediction it says `No Spans found returning the doc as is`. The debugger on DocBin of my test sentence is not showing any entities. 

_I tried to Predict something from my sentence which Is in the training dataset. But It's still the same._

**Questions

1.  Is the model that is trained, is trained to predict only the relations not the entities?
2. Are the entities need to be trained on different NER model and load that NER Model to predict entities here? 
3. Output model config file doesn't show my entities which needs relation. They only display the relation labels. Why is that happening?** 

I think I'm close to it. Can you please help with this and let me know where I'm going wrong. 

Please take a look the at Screenshot for additional reference. 

<img width="1440" alt="Screen Shot 2022-03-25 at 6 22 41 AM" src="https://user-images.githubusercontent.com/63583829/160033760-ab17611a-842e-4598-b982-1e3d20345f12.png">

**Comment by AdirthaBorgohain** [comment]
Hi Sraavan. You get the issue ``No Spans found returning the doc as is`` when there are no entities detected by the NER. In such case, the relation extraction model has no entities to predict relations between. In short, to get predictions from the relation extraction model, you actually need two models - NER and Relation Extraction Model. In my codebase, both these models are separate and need to be separately trained. You can combine both NER and Relation Extraction into a single model itself while training, but in my case it didn't give me good results as both NER and Relation Extraction Model use a common shared layer in this case (either tok2vec or transformers).

Answers to your questions:
1. The model that is trained is trained to predict only relations and not entities. However it expects entities to be predicted by some NER model before it can predict relations on them.
2.  Yes. Exactly. If you want, you can actually use the same training data for training a NER model as well, I'd suggest going through the ``project.yml`` file inside the NER directory in this case. The steps are similar to how you train the relation extraction model. To see how you can combine the two during inference, you can check the ``PipelineModel.py`` file.  I just updated a few things today so that it is easier to follow. 
3. That's because you have only trained the relation extraction model. You will need separate training for the NER model.

Let me know if you have difficulties understanding it.
